// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoZvcXbKmZ5-3fLPbKhfNyPuBX-liPuKA',
    appId: '1:610487055303:web:dd5b1f641cf07611c29fe2',
    messagingSenderId: '610487055303',
    projectId: 'tracker-59470',
    authDomain: 'tracker-59470.firebaseapp.com',
    databaseURL: 'https://tracker-59470-default-rtdb.firebaseio.com',
    storageBucket: 'tracker-59470.appspot.com',
    measurementId: 'G-R67WGDKJLG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIFQx3Cd5B48EeHmsC9tcnDsJSOQk1JKA',
    appId: '1:610487055303:android:87ca5d6c6d72a911c29fe2',
    messagingSenderId: '610487055303',
    projectId: 'tracker-59470',
    databaseURL: 'https://tracker-59470-default-rtdb.firebaseio.com',
    storageBucket: 'tracker-59470.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArE5rN0uOmeyL_A7gSOcYMEXOVzBaeRqA',
    appId: '1:610487055303:ios:e201afe5e6437c4ec29fe2',
    messagingSenderId: '610487055303',
    projectId: 'tracker-59470',
    databaseURL: 'https://tracker-59470-default-rtdb.firebaseio.com',
    storageBucket: 'tracker-59470.appspot.com',
    iosClientId: '610487055303-93poadn6ievackmqap77anoj8eclpavu.apps.googleusercontent.com',
    iosBundleId: 'com.example.trackerHabit',
  );
}